# Generated by Django 3.0.4 on 2022-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200430_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fees_in_usa',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fess_in_world',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.CharField(default='', max_length=100, verbose_name='Кинопоиск'),
        ),
        migrations.AddField(
            model_name='movie',
            name='torrent_id',
            field=models.CharField(default='', max_length=100, verbose_name='Торрент'),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_id',
            field=models.CharField(default='', max_length=100, verbose_name='Ютуб'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='', max_length=100, verbose_name='Актёры'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(default='', max_length=100, verbose_name='Режиссёр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, verbose_name='Дата выхода'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='MovieShots',
        ),
    ]
