# Generated by Django 3.0.4 on 2022-07-08 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220708_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(default='defolt.jpg', upload_to='actors/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Актеры и режиссеры',
                'verbose_name_plural': 'Актеры и режиссеры',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='kinopoisk_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='torrent_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AddField(
            model_name='movie',
            name='fess_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='defolt.jpg', upload_to='movies/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=100, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Примьера в мире'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Дата выхода'),
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Изображение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры из фильма',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movies.Actor', verbose_name='актеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='film_director', to='movies.Actor', verbose_name='режиссер'),
        ),
    ]
