# Generated by Django 3.0.4 on 2022-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220708_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='torrent_id',
            field=models.TextField(default='', verbose_name='Торрент'),
        ),
    ]
